namespace Bastion.Client.Screens;

public enum ScreenId
{
    Login,
    Register,
    ForgotPassword,
    ResetPassword,
    AccountSettings,
    ChangePassword,
    ChangeEmail,
    ChangeNickname,
    DeleteAccount,
    ActiveSessions,
    RegistrationSuccess,
    Profile,
    EditProfile,
    PlayerCard,
    Friends,
    AddFriend,
    MatchHistory,
    CoinHistory,
    Leaderboard,
    Report,
    ModerationQueue,
    ReportReview,
    ApplySanction,
    Appeal,
    AdminPanel,
    Logs,
    Shop,
    PurchaseConfirm,
    BoxPurchaseConfirm,
    Customize,
    SettingsLanguage,

    MainScreen,
    PendingVerification,
    SecondFactor,
    BannedAccount,
    FirstTime,
    LinkAccount,

    MainMenu,
    SelectMode,
    Matchmaking,
    VersusScreen,
    Match,
    MatchEnd,
    OpponentDisconnected,
    PrivateMatch,
    WaitingRoom,
    AIDifficulty,
    AIMatchEnd,
    Spectator,
    Replay,
    TutorialIndex
}
